"""Remove pytest/py caches under M6.2Q so the staged tree carries no generated bytecode."""
import os, shutil

DST = r"D:\M6\Module6-workspace\01-coder\04-artifacts\impl\M6.2Q"
removed = {"__pycache__": 0, ".pytest_cache": 0, ".pyc": 0}
for dp, dns, fns in os.walk(DST, topdown=False):
    for d in list(dns):
        if d in ("__pycache__", ".pytest_cache", ".mypy_cache"):
            shutil.rmtree(os.path.join(dp, d), ignore_errors=True)
            removed["__pycache__" if d == "__pycache__" else ".pytest_cache"] += 1
    for f in fns:
        if f.endswith((".pyc", ".pyo")):
            try:
                os.remove(os.path.join(dp, f)); removed[".pyc"] += 1
            except OSError:
                pass

def count(root, ext=None):
    c = 0
    for dp, dns, fns in os.walk(root):
        for f in fns:
            if ext is None or f.endswith(ext):
                c += 1
    return c

print("cache dirs/files removed:", removed)
print("residual __pycache__ dirs:", sum(1 for dp,dns,fns in os.walk(DST) if os.path.basename(dp)=="__pycache__"))
print("residual .pytest_cache  :", sum(1 for dp,dns,fns in os.walk(DST) if os.path.basename(dp)==".pytest_cache"))
print("M6.2Q total files:", count(DST), " .py:", count(DST, ".py"), " .sql:", count(DST, ".sql"))
